name: VHDL Testbenches

on:
  push:
    paths:
      - vhdl/**
  pull_request:
    paths:
      - vhdl/**

jobs:
  run_testbenches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Install dependencies with apt
        run: sudo apt-get install ghdl zip -y

      - name: Install Python dependencies
        run: pip install --user pipenv

      - name: Setup Python Virtual Environment
        run: pipenv install

      - name: Compile VHDL
        run: pipenv run python3 run.py --compile
        working-directory: ./vhdl

      - name: Run Tests
        run: pipenv run python3 run.py --gtkwave-fmt=ghw
        working-directory: ./vhdl

      - name: Compress Results
        run: zip -r results.zip vhdl/vunit_out/test_output
        if: ${{ failure() }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v6
        if: ${{ failure() }}
        with:
          name: test_results
          path: results.zip
